### ISSUE TITLE
UnsupportedOperationException when reading String blocks

### ISSUE THREAD

**Issue by bogovicj** [saalfeldlab/n5-blosc#7]
Updating to n5-3.1.1 and running tests result in this error:

```
[ERROR] org.janelia.saalfeldlab.n5.blosc.BloscCompressionTest.testWriteReadStringBlock -- Time elapsed: 0.010 s <<< ERROR!
java.lang.UnsupportedOperationException
	at java.nio.ByteBuffer.array(ByteBuffer.java:1002)
	at org.janelia.saalfeldlab.n5.StringDataBlock.readData(StringDataBlock.java:58)
	at org.janelia.saalfeldlab.n5.blosc.BloscCompression.read(BloscCompression.java:157)
	at org.janelia.saalfeldlab.n5.DefaultBlockReader.readBlock(DefaultBlockReader.java:95)
	at org.janelia.saalfeldlab.n5.GsonKeyValueN5Reader.readBlock(GsonKeyValueN5Reader.java:101)
	at org.janelia.saalfeldlab.n5.AbstractN5Test.testWriteReadStringBlock(AbstractN5Test.java:226)
```

**Comment by minnerbe** [comment]
Yes, unfortunately that happens in the deserialization logic of `StringDataBlock`. The problem seems to be (as explained by @mkitti) that `ByteBuffer.array()` is optional and apparently not implemented by whatever blosc is using. Seems like this was already fixed by @bogovicj in [this PR](https://github.com/saalfeldlab/n5/pull/113). :pray:

**Comment by bogovicj** [comment]
fixed by https://github.com/saalfeldlab/n5/pull/113
